### ISSUE TITLE
Trouble getting it up and running

### ISSUE THREAD

**Issue by jvanbaarsen** [balvig/motion-hybrid#4]
Hi,

Probably I'm doing something wrong since I just started out with RubyMotion, but I followed the readme and now I'm getting the following error in my app when starting (On simulator and device)

```
(main)> 2015-08-17 19:03:41.110 Hello[98464:8109014] styleable.rb:36:in `set_webview_options': undefined method `scrollView' for nil:NilClass (NoMethod
Error)
        from styleable.rb:8:in `on_init'
        from support.rb:17:in `try:'
        from screen_module.rb:19:in `screen_init:'
        from view_controller.rb:5:in `new:'
        from app_delegate.rb:3:in `on_load:'
        from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
2015-08-17 19:03:41.120 Hello[98464:8109014] *** Terminating app due to uncaught exception 'NoMethodError', reason: 'styleable.rb:36:in `set_webview_op
tions': undefined method `scrollView' for nil:NilClass (NoMethodError)
        from styleable.rb:8:in `on_init'
        from support.rb:17:in `try:'
        from screen_module.rb:19:in `screen_init:'
        from view_controller.rb:5:in `new:'
        from app_delegate.rb:3:in `on_load:'
        from delegate_module.rb:16:in `application:didFinishLaunchingWithOptions:'
```

I hope you can point me in the right direction! My simulator is running version 8.4

**Comment by fiedl** [comment]
Hi @balvig, this appears to be a great tool! Unfortunately, I've got the same issue as jvanbaarsen.

## How to reproduce

```
git clone git@github.com:balvig/motion-hybrid.git
cd motion-hybrid

bundle install
pod setup
rake pod:install  # reports a conflict

rm vendor/Podfile.lock
rake pod:install

rake  # raises the error of this issue
```

## Versions

```
➜  ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]

➜  motion --version
4.1

➜  pod --version
0.38.2
```

On Yosemite 10.10.5 (14F27), XCode Version 7.0 (7A220).

**Comment by balvig** [comment]
Really sorry to let you down @jvanbaarsen and @fiedl, the truth is I haven't used RubyMotion for a long time and don't even have the latest version anymore so am unable to test/hack on it... :bow: 

It looks like maybe an incompatibility with the latest version of ProMotion, that's what I get for not specifying version numbers in the gemspec! :sweat: 

I know I had it running against ver `1.2.1`, maybe you could try locking the project to that to see if that helps?

**Comment by jvanbaarsen** [comment]
@balvig Thanks for replying :-) Tomorrow I have some time to test this. I'll let you know!

**Comment by fiedl** [comment]
I've settled with ProMotion web screens, now.

https://github.com/infinitered/ProMotion

![68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313437393231352f313533343633312f66666531623336612d346339372d313165332d386338662d6337623134653236313832642e706e67](https://cloud.githubusercontent.com/assets/1679688/10156570/fc273676-6682-11e5-83a9-082dc7384ab3.png)
